const actions = {
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  VIEW_CLIENTS: "VIEW_CLIENTS",
  CREATE_USER: "CREATE_USER",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  CREATE_PRODUCTS: "CREATE_PRODUCTS",
  CREATE_ORDER: "CREATE_ORDER",
  CREATE_CLIENTS: "CREATE_CLIENTS",
  VIEW_ORDERS: "VIEW_ORDERS",
  SET_PACKAGED: "SET_PACKAGED",
  SET_PAYED: "SET_PAYED",
  EDIT_USERS: "EDIT_USERS",
};

const roles = {
  ADMIN: "ADMIN",
  SALES: "SALES",
  PACKAGER: "PACKAGER",
};

export { actions, roles };
