
const actions = {
    VIEW_PRODUCTS: "VIEW_PRODUCTS",
    CREATE_USER: "CREATE_USER",
    DELETE_PRODUCTS: "DELETE_PRODUCTS",
    UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
    CREATE_PRODUCTS: "CREATE_PRODUCTS",
    CREATE_ORDER: "CREATE_ORDER",
    CREATE_CLIENTS: "CREATE_CLIENTS",
    VIEW_ORDERS: "VIEW_ORDERS" 
  };
  
  const roles = {
    ADMIN: "ROLE_ADMIN",
    SALES: "ROLE_SALES",
    PACKAGER: "ROLE_PACKAGER"
  };
  


  export { actions, roles };